### ISSUE TITLE
NameError: uninitialized constant ClickhouseActiverecord::Migrator when running `db:schema:load`

### ISSUE THREAD

**Issue by grk** [PNixx/clickhouse-activerecord#108]
Running clickhouse-activerecord 1.0.1 on Rails 7.1.2. When I want to load the schema in test mode (or CI), I encounter the following error:

```
** Execute db:schema:load
bin/rails aborted!
NameError: uninitialized constant ClickhouseActiverecord::Migrator (NameError)

        connection.assume_migrated_upto_version(info[:version], ClickhouseActiverecord::Migrator.migrations_paths)
                                                                                      ^^^^^^^^^^
/Users/grk/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/clickhouse-activerecord-1.0.1/lib/clickhouse-activerecord/schema.rb:12:in `define'
/Users/grk/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0/gems/activerecord-7.1.2/lib/active_record/schema.rb:50:in `define'
/Users/grk/code/mh-platform/db/clickhouse_measurements_schema.rb:13:in `<main>'
```

Which makes sense since there's no class for ClickhouseActiverecord::Migrator defined.

**Comment by PNixx** [comment]
`rake clickhouse:schema:load` working?

**Comment by grk** [comment]
Thanks!
