### ISSUE TITLE
Rails 6 can not create table for schema_migrations

### ISSUE THREAD

**Issue by StoneGod** [PNixx/clickhouse-activerecord#14]
I try to run `bundle exec rails db:migrate`, but got this error.

```
bundle exec rails db:migrate
2019-09-09T17:51:50.157+04:00 rake/db:migrate 71tNxhgP INFO - Invoked with args: []
2019-09-09T17:51:50.433991+04:00 rake/db:migrate 71tNxhgP DEBUG - Sidekiq client with redis options {:url=>"redis://localhost:6379/10", :id=>nil}
2019-09-09T17:51:52.351356+04:00 rake/db:migrate 71tNxhgP DEBUG - PID:1500    (0.2ms)  SELECT pg_try_advisory_lock(1792134317172985800)
2019-09-09T17:51:52.356472+04:00 rake/db:migrate 71tNxhgP DEBUG - PID:1500    (0.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
2019-09-09T17:51:52.361035+04:00 rake/db:migrate 71tNxhgP DEBUG - PID:1500   ActiveRecord::InternalMetadata Load (0.3ms)  SELECT "ar_internal_metadata".* FROM "ar_internal_metadata" WHERE "ar_internal_metadata"."key" = $1 LIMIT $2  [["key", "environment"], ["LIMIT", 1]]
2019-09-09T17:51:52.364688+04:00 rake/db:migrate 71tNxhgP DEBUG - PID:1500    (0.2ms)  SELECT pg_advisory_unlock(1792134317172985800)
2019-09-09T17:51:52.376619+04:00 rake/db:migrate 71tNxhgP DEBUG - PID:1500   Clickhouse  (system) (3.8ms)  SHOW TABLES
2019-09-09T17:51:52.378694+04:00 rake/db:migrate 71tNxhgP DEBUG - PID:1500   Clickhouse  (1.8ms)  CREATE TABLE {:id=>false} (version String) ENGINE = Log()
2019-09-09T17:51:52.378818+04:00 rake/db:migrate 71tNxhgP FATAL - ActiveRecord::StatementInvalid: ActiveRecord::ActiveRecordError: Response code: 400: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 14: {:id=>false} (version String) ENGINE = Log() FORMAT JSONCompact. Expected one of: identifier, IF NOT EXISTS (version 19.13.1.11 (official build))  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/clickhouse-activerecord-0.3.8/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:109:in `process_response';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/clickhouse-activerecord-0.3.8/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:100:in `block in do_execute';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:707:in `block (2 levels) in log';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:706:in `block in log';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract_adapter.rb:697:in `log';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/clickhouse-activerecord-0.3.8/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:96:in `do_execute';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/clickhouse-activerecord-0.3.8/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:8:in `execute';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/connection_adapters/abstract/schema_statements.rb:315:in `create_table';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/schema_migration.rb:33:in `create_table';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1206:in `initialize';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1061:in `new';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1061:in `up';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/migration.rb:1036:in `migrate';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/tasks/database_tasks.rb:238:in `migrate';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:85:in `block (3 levels) in <top (required)>';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:83:in `each';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/databases.rake:83:in `block (2 levels) in <top (required)>';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/2.6.0/monitor.rb:230:in `mon_synchronize';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/unilog-2.3.0/lib/unilog/rake_logging.rb:7:in `block in invoke';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/unilog-2.3.0/lib/unilog.rb:92:in `within_context';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/unilog-2.3.0/lib/unilog/rake_logging.rb:4:in `invoke';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:23:in `block in perform';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/commands/rake/rake_command.rb:20:in `perform';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/command.rb:48:in `invoke';  /Users/stonegod/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>';  bin/rails:4:in `require';  bin/rails:4:in `<main>'
2019-09-09T17:51:52.379091+04:00 - 1500 DEBUG - PID:1500 ActiveRecord::ActiveRecordError: Response code: 400: Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 14: {:id=>false} (version String) ENGINE = Log() FORMAT JSONCompact. Expected one of: identifier, IF NOT EXISTS (version 19.13.1.11 (official build))  excluded from capture: Not configured to send/capture in environment 'default'
rails aborted!
ActiveRecord::StatementInvalid: ActiveRecord::ActiveRecordError: Response code: 400:
Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 14: {:id=>false} (version String) ENGINE = Log() FORMAT JSONCompact. Expected one of: identifier, IF NOT EXISTS (version 19.13.1.11 (official build))
bin/rails:4:in `require'
bin/rails:4:in `<main>'
```

**Comment by xTRiM** [comment]
@PNixx which ClickHouse version do you use? I'm getting same error as @StoneGod but on 19.16.2.2 (latest)

**Comment by PNixx** [comment]
ClickHouse gem not fully support with Rails 6

**Comment by StoneGod** [comment]
I fixed this in fork https://github.com/StoneGod/clickhouse-activerecord
but it's work only with rails 6.0.0, in 6.0.1 it's crush

**Comment by StoneGod** [comment]
@xTRiM I updated fork. It's work with rails 6.0.1 now.

**Comment by PNixx** [comment]
@StoneGod please create pull request

**Comment by mikefaraponov** [comment]
@StoneGod please create pull request +1 and maybe add support for alternative migrations paths from database.yml like in Rails 6.0 way 
```
   development:
       primary:
       clickhouse:
             migrations_path: blabla
```

**Comment by StoneGod** [comment]
I will try on Sunday. But I can’t guarantee it because it was based on [another fork](https://github.com/portmare/clickhouse-activerecord)

**Comment by mikefaraponov** [comment]
@StoneGod, Maybe you have some kind of coffee buymeacoffee.com or smth like that, I will be more than happy to buy you one cup of coffee, tea, whatever to make your work easier)

**Comment by StoneGod** [comment]
@mikefaraponov Yes, I have https://www.buymeacoffee.com/ONEhT2p
