### ISSUE TITLE
Strange error with query

### ISSUE THREAD

**Issue by arrowcircle** [PNixx/clickhouse-activerecord#3]
Hello!

I tried to use this gem with clickhouse, but cant make it work. Here is the result from console.

```
Sensor::Reading.first
  Clickhouse Sensor::Reading Load (88.1ms)  SELECT  sensor_readings.* FROM sensor_readings ORDER BY sensor_readings.id ASC LIMIT 1
Traceback (most recent call last):
        1: from (irb):1
ActiveRecord::StatementInvalid (ActiveRecord::ActiveRecordError: Response code: 404:)
Code: 60, e.displayText() = DB::Exception: Table myapp_development.sensor_readings doesn't exist., e.what() = DB::Exception
: SELECT  sensor_readings.* FROM sensor_readings ORDER BY sensor_readings.id ASC LIMIT 1
```
I created table with 'clickhouse' gem with this migration:

```
require 'clickhouse'
Clickhouse.logger = Logger.new(STDOUT)

class CreateSensorReadings < ActiveRecord::Migration[5.2]
  def up
    Clickhouse.establish_connection
    Clickhouse.connection.create_table('sensor_readings') do |t|
      t.fixed_string :id, 16
      t.date_time    :created_at
      t.date         :created_at_date
      t.uint32       :sensor_id
      t.float32      :temperature
      t.float32      :pressure
      t.engine       "MergeTree(created_at_date, (created_at_date), 8192)"
    end
  end

  def down
    Clickhouse.establish_connection
    Clickhouse.connection.execute("DROP TABLE IF EXISTS sensor_readings")
  end
end
```
Table is created, if I run in console:
```
Clickhouse.connection.query "select sensor_readings.* FROM sensor_readings ORDER BY created_at ASC LIMIT 1"
 => #<Clickhouse::Connection::Query::ResultSet:0x00007fb531ac83c8 @rows=[], @names=["id", "created_at", "created_at_date", "sensor_id", "temperature", "pressure"], @types=["FixedString(16)", "DateTime", "Date", "UInt32", "Float32", "Float32"]>

Clickhouse.connection.execute('show tables')
 => "sensor_readings\n"
```

What I doing wrong?

**Comment by PNixx** [comment]
I think you need use 
```
Sensor::Reading.establish_connection
Sensor::Reading..connection.create_table('sensor_readings') do |t|
***
```

**Comment by arrowcircle** [comment]
It does not work
```
== 20180815191056 CreateSensorReadings: migrating =============================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

undefined method `fixed_string' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x00007feaefe98e28>
/Users/user/projects/work/myapp/db/migrate/20180815191056_create_sensor_readings.rb:8:in `block in up'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:305:in `create_table'
/Users/user/projects/work/myapp/db/migrate/20180815191056_create_sensor_readings.rb:7:in `up'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:817:in `exec_migration'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:796:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:977:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `each'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1036:in `up'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1011:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/bin/ruby_executable_hooks:24:in `<main>'

Caused by:
NoMethodError: undefined method `fixed_string' for #<ActiveRecord::ConnectionAdapters::TableDefinition:0x00007feaefe98e28>
/Users/user/projects/work/myapp/db/migrate/20180815191056_create_sensor_readings.rb:8:in `block in up'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/schema_statements.rb:305:in `create_table'
/Users/user/projects/work/myapp/db/migrate/20180815191056_create_sensor_readings.rb:7:in `up'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:817:in `exec_migration'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:798:in `block (2 levels) in migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:797:in `block in migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:414:in `with_connection'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:796:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:977:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1292:in `block in execute_migration_in_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1343:in `block in ddl_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `block in transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:239:in `block in within_new_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/transaction.rb:236:in `within_new_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/connection_adapters/abstract/database_statements.rb:254:in `transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/transactions.rb:212:in `transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1343:in `ddl_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1291:in `execute_migration_in_transaction'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1263:in `block in migrate_without_lock'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `each'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1262:in `migrate_without_lock'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `block in migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1363:in `with_advisory_lock'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1210:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1036:in `up'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/migration.rb:1011:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/tasks/database_tasks.rb:172:in `migrate'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/activerecord-5.2.1/lib/active_record/railties/databases.rake:60:in `block (2 levels) in <main>'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/bin/ruby_executable_hooks:24:in `eval'
/Users/user/.rvm/gems/ruby-2.5.1@myapp/bin/ruby_executable_hooks:24:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

**Comment by arrowcircle** [comment]
I found whats caused the problem. I added db name as a prefix for table name and it works now.

**Comment by PNixx** [comment]
Please, write your example.

**Comment by arrowcircle** [comment]
For database creation its needed to remove database key from configuration hash. No need for that in create table migration.
create_clickhouse_database.rb
```
require 'clickhouse'
Clickhouse.logger = Logger.new(STDOUT)

class CreateClickhouseDatabase < ActiveRecord::Migration[5.2]
  def up
    db_config = Rails.configuration.database_configuration["clickhouse_#{Rails.env}"]
    Clickhouse.establish_connection(db_config.except('database'))
    Clickhouse.connection.execute("CREATE DATABASE IF NOT EXISTS #{db_config['database']}")
  end

  def down
    db_config = Rails.configuration.database_configuration["clickhouse_#{Rails.env}"]
    Clickhouse.establish_connection(db_config.except('database'))
    Clickhouse.connection.execute("DROP DATABASE IF EXISTS #{db_config['database']}")
  end
end
```

create_sensor_readings.rb
```
require 'clickhouse'
Clickhouse.logger = Logger.new(STDOUT)

class CreateSensorReadings < ActiveRecord::Migration[5.2]
  def up
    Clickhouse.establish_connection(Rails.configuration.database_configuration["clickhouse_#{Rails.env}"])
    Clickhouse.connection.create_table("#{ActiveRecord::Base.connection.current_database}.sensor_readings") do |t|
      t.fixed_string :id, 16
      t.date_time    :created_at
      t.date         :created_at_date
      t.uint32       :sensor_id
      t.float32      :temperature
      t.float32      :pressure
      t.engine       "MergeTree(created_at_date, (created_at_date), 8192)"
    end
  end

  def down
    Clickhouse.establish_connection(Rails.configuration.database_configuration["clickhouse_#{Rails.env}"])
    Clickhouse.connection.execute("DROP TABLE IF EXISTS #{ActiveRecord::Base.connection.current_database}.sensor_readings")
  end
end

```

Other tricky problem I got is transactional fixtures. CH dont support transactions, and tests use them for faster tests execution. Don't know yet how to fix this.
Here is logs from rspec output

```
5) Sensor::Updater ignores negative periods
     Failure/Error: Sensor::Reading.create(clickhouse_payload)

     ActiveRecord::StatementInvalid:
       ActiveRecord::ActiveRecordError: Response code: 500:
       Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1: SAVEPOINT active_record_1 FORMAT JSONCompact
       . Expected one of: CREATE TABLE or ATTACH TABLE query, SELECT query, possibly with UNION, SHOW [TEMPORARY] TABLES|DATABASES [[NOT] LIKE 'str'], SELECT query, subquery, possibly with UNION, Query, DROP, DETACH, ATTACH, list of elements, ALTER query, ALTER TABLE, WITH, CREATE, Query with output, SHOW PROCESSLIST query, SHOW PROCESSLIST, RENAME query, RENAME TABLE, SET query, SET, SHOW, SYSTEM query, EXISTS or SHOW CREATE query, EXISTS, DESCRIBE, DESC, USE query, USE, SELECT subquery, CHECK TABLE, DESCRIBE query, DROP query, TRUNCATE, INSERT query, INSERT INTO, SELECT, KILL QUERY query, KILL QUERY, OPTIMIZE query, OPTIMIZE TABLE, SELECT query, e.what() = DB::Exception
       : SAVEPOINT active_record_1
     # /Users/user/.rvm/gems/ruby-2.5.1@sensorhub/gems/clickhouse-activerecord-0.2.1/lib/active_record/connection_adapters/clickhouse_adapter.rb:133:in `query'
     # /Users/user/.rvm/gems/ruby-2.5.1@sensorhub/gems/clickhouse-activerecord-0.2.1/lib/active_record/connection_adapters/clickhouse_adapter.rb:139:in `block in execute'
     # /Users/user/.rvm/gems/ruby-2.5.1@sensorhub/gems/clickhouse-activerecord-0.2.1/lib/active_record/connection_adapters/clickhouse_adapter.rb:138:in `execute'
     # ./app/models/sensor/updater.rb:31:in `insert_data'
     # ./app/models/sensor/updater.rb:13:in `run'
     # ./spec/models/sensor_updater_spec.rb:47:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # ActiveRecord::ActiveRecordError:
     #   Response code: 500:
     #   Code: 62, e.displayText() = DB::Exception: Syntax error: failed at position 1: SAVEPOINT active_record_1 FORMAT JSONCompact
     #   . Expected one of: CREATE TABLE or ATTACH TABLE query, SELECT query, possibly with UNION, SHOW [TEMPORARY] TABLES|DATABASES [[NOT] LIKE 'str'], SELECT query, subquery, possibly with UNION, Query, DROP, DETACH, ATTACH, list of elements, ALTER query, ALTER TABLE, WITH, CREATE, Query with output, SHOW PROCESSLIST query, SHOW PROCESSLIST, RENAME query, RENAME TABLE, SET query, SET, SHOW, SYSTEM query, EXISTS or SHOW CREATE query, EXISTS, DESCRIBE, DESC, USE query, USE, SELECT subquery, CHECK TABLE, DESCRIBE query, DROP query, TRUNCATE, INSERT query, INSERT INTO, SELECT, KILL QUERY query, KILL QUERY, OPTIMIZE query, OPTIMIZE TABLE, SELECT query, e.what() = DB::Exception
     #   /Users/user/.rvm/gems/ruby-2.5.1@sensorhub/gems/clickhouse-activerecord-0.2.1/lib/active_record/connection_adapters/clickhouse_adapter.rb:133:in `query'
```

And here is log from test execution. Interesting line is "Clickhouse  (65.7ms)  SAVEPOINT active_record_1"

```
(4.5ms)  SELECT "schema_migrations"."version" FROM "schema_migrations" ORDER BY "schema_migrations"."version" ASC
   (1.1ms)  BEGIN
   (1.2ms)  SAVEPOINT active_record_1
  Sensor Exists (5.9ms)  SELECT  1 AS one FROM "sensors" WHERE "sensors"."uid" = $1 LIMIT $2  [["uid", "d07d27d6e8ba2a4b541f1cb8aedec5c8"], ["LIMIT", 1]]
  Sensor Create (2.7ms)  INSERT INTO "sensors" ("uid", "name", "last_contacted_at", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["uid", "d07d27d6e8ba2a4b541f1cb8aedec5c8"], ["name", "Margeret Cummings"], ["last_contacted_at", "2018-08-16 07:48:49.480823"], ["created_at", "2018-08-16 07:48:49.490085"], ["updated_at", "2018-08-16 07:48:49.490085"]]
   (0.8ms)  RELEASE SAVEPOINT active_record_1
  Sensor Load (2.1ms)  SELECT  "sensors".* FROM "sensors" WHERE "sensors"."uid" = $1 LIMIT $2  [["uid", "d07d27d6e8ba2a4b541f1cb8aedec5c8"], ["LIMIT", 1]]
   (0.7ms)  SAVEPOINT active_record_1
  Sensor Exists (3.0ms)  SELECT  1 AS one FROM "sensors" WHERE "sensors"."uid" = $1 AND "sensors"."id" != $2 LIMIT $3  [["uid", "d07d27d6e8ba2a4b541f1cb8aedec5c8"], ["id", 52], ["LIMIT", 1]]
  Sensor Update (2.6ms)  UPDATE "sensors" SET "last_contacted_at" = $1, "period" = $2, "updated_at" = $3 WHERE "sensors"."id" = $4  [["last_contacted_at", "2018-08-17 07:48:49.495077"], ["period", 86400], ["updated_at", "2018-08-16 07:48:49.505524"], ["id", 52]]
   (0.6ms)  RELEASE SAVEPOINT active_record_1
  Clickhouse  (65.7ms)  SAVEPOINT active_record_1
   (1.1ms)  ROLLBACK
```

Any ideas how to fix it?

**Comment by PNixx** [comment]
Thanks for your example.
For spec you can try to use `config.use_transactional_fixtures = false`

**Comment by arrowcircle** [comment]
disabling transactional fixtures for simple unit tests will slower them significantly, so its last option.
