### ISSUE TITLE
Rails 6.1.0 incompatible: uninitialized constant ActiveRecord::MigrationContext (NameError)

### ISSUE THREAD

**Issue by jbwl** [PNixx/clickhouse-activerecord#40]
I upgraded my bundle to Rails 6.1.3 (API mode) from 6.0.3.5. The application fails to start using clickhouse-activerecord gem 0.4.8 with the error below. ActiveRecord::MigrationContext seems to have been deprecated.

```
/Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clickhouse-activerecord-0.4.8/lib/clickhouse-activerecord/migration.rb:40:in `<module:ClickhouseActiverecord>': uninitialized constant ActiveRecord::MigrationContext (NameError)
```

Backtrace:

```
Traceback (most recent call last):
	56: from /Users/dev11/projects/project/bin/rails:3:in `<main>'
	55: from /Users/dev11/projects/project/bin/rails:3:in `load'
	54: from /Users/dev11/projects/project/bin/spring:15:in `<top (required)>'
	53: from /Users/dev11/projects/project/bin/spring:15:in `require'
	52: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `<top (required)>'
	51: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/binstub.rb:11:in `load'
	50: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/bin/spring:49:in `<top (required)>'
	49: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client.rb:30:in `run'
	48: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/command.rb:7:in `call'
	47: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `call'
	46: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/spring-2.1.1/lib/spring/client/rails.rb:28:in `load'
	45: from /Users/dev11/projects/project/bin/rails:9:in `<top (required)>'
	44: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	43: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	42: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	41: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	40: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	39: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands.rb:18:in `<main>'
	38: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/command.rb:50:in `invoke'
	37: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/command/base.rb:69:in `perform'
	36: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	35: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	34: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	33: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/server/server_command.rb:135:in `perform'
	32: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/server/server_command.rb:135:in `tap'
	31: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.3/lib/rails/commands/server/server_command.rb:138:in `block in perform'
	30: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	29: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	28: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	27: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	26: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	25: from /Users/dev11/projects/project/config/application.rb:20:in `<main>'
	24: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler.rb:174:in `require'
	23: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:50:in `require'
	22: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:50:in `each'
	21: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:61:in `block in require'
	20: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:61:in `each'
	19: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/site_ruby/2.7.0/bundler/runtime.rb:66:in `block (2 levels) in require'
	18: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	17: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	16: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	15: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	14: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	13: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clickhouse-activerecord-0.4.8/lib/clickhouse-activerecord.rb:3:in `<main>'
	12: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	11: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	10: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 9: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 8: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 7: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clickhouse-activerecord-0.4.8/lib/active_record/connection_adapters/clickhouse_adapter.rb:5:in `<main>'
	 6: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 5: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 4: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 3: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 2: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.7.2/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 1: from /Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clickhouse-activerecord-0.4.8/lib/clickhouse-activerecord/migration.rb:1:in `<main>'
/Users/dev11/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/clickhouse-activerecord-0.4.8/lib/clickhouse-activerecord/migration.rb:40:in `<module:ClickhouseActiverecord>': uninitialized constant ActiveRecord::MigrationContext (NameError)
```

**Comment by ferrucc-io** [comment]
This PR seems to be working for some people using Rails 6.1

**Comment by jbwl** [comment]
Unfortunately, using the master branch for the gem (including the PR) hasn't fixed the startup problem for me (same error as above).

**Comment by zabodaevmm** [comment]
How about rename clickhouse-activerecord and clickhouse-activerecord.rb in snake-case style
