### ISSUE TITLE
Rails 7 migrations issue: ActiveRecord::ActiveRecordError: Clickhouse update is not supported

### ISSUE THREAD

**Issue by sadgb** [PNixx/clickhouse-activerecord#84]
Hi there

Thanks for all your work. Sorry if my question is stupid, but i have strange problem when trying to migrate my database

```
bundle exec rails db:migrate:clickhouse    
Running via Spring preloader in process 66384
rake aborted!
ActiveRecord::ActiveRecordError: Clickhouse update is not supported
```

I see from other issues that there are some problems even with Rails 6 migrations, but maybe there are some workarounds / tricks with database.yml config ?

**Comment by PNixx** [comment]
You can not use update in ClickHouse. Please, show your migration file.

**Comment by sadgb** [comment]
Yep, i know, but it looks like my migrations isnt using any

```
# frozen_string_literal: true

class CreateCurrencyPrices < ActiveRecord::Migration[7.0]
  def up
    table_options = 'MergeTree PRIMARY KEY(code, at)'

    create_table :currency_prices, id: false, options: table_options, if_not_exists: true do |t|
      t.string :code, null: false, limit: 8
      t.decimal :usd_price, null: false, limit: 32, precision: 76, scale: 38
      t.datetime :at, null: false, limit: 8
    end
  end

  def down; end
end
```

The error i got is:

`rake db:migrate:clickhouse
DEBUGGER[spring app    | test | started 18 hours ago | development mode#76786]: Attaching after process 62721 fork to child process 76786
Running via Spring preloader in process 76786
rake aborted!
ActiveRecord::ActiveRecordError: Clickhouse update is not supported
/Users/user/.rvm/gems/ruby-3.1.2@test/bundler/gems/clickhouse-activerecord-5e5464a3dd96/lib/active_record/connection_adapters/clickhouse/schema_statements.rb:34:in `exec_update'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:175:in `update'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/query_cache.rb:22:in `update'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/persistence.rb:513:in `_update_record'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/persistence.rb:1058:in `_update_row'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/locking/optimistic.rb:88:in `_update_row'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/persistence.rb:1080:in `_update_record'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/attribute_methods/dirty.rb:216:in `_update_record'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/callbacks.rb:465:in `block in _update_record'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:929:in `_run_update_callbacks'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/callbacks.rb:465:in `_update_record'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/timestamp.rb:121:in `_update_record'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/persistence.rb:1067:in `create_or_update'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/callbacks.rb:457:in `block in create_or_update'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:99:in `run_callbacks'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:929:in `_run_save_callbacks'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/callbacks.rb:457:in `create_or_update'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/timestamp.rb:126:in `create_or_update'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/persistence.rb:648:in `save!'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/validations.rb:53:in `save!'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/transactions.rb:302:in `block in save!'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:314:in `transaction'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/transactions.rb:302:in `save!'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/suppressor.rb:54:in `save!'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/persistence.rb:780:in `block in update!'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activesupport-7.0.4/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/connection_adapters/abstract/database_statements.rb:316:in `transaction'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/persistence.rb:778:in `update!'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/internal_metadata.rb:31:in `[]='
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/migration.rb:1341:in `record_environment'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/migration.rb:1334:in `migrate_without_lock'
/Users/user/.rvm/gems/ruby-3.1.2@test/gems/activerecord-7.0.4/lib/active_record/migration.rb:1284:in `migrate'
/Users/user/.rvm/gems/ruby-3.1.2@test/bundler/gems/clickhouse-activerecord-5e5464a3dd96/lib/clickhouse-activerecord/migration.rb:79:in `up'`

**Comment by PNixx** [comment]
Maybe you need configure https://github.com/PNixx/clickhouse-activerecord#usage-in-rails-6-with-second-database?

**Comment by PNixx** [comment]
Try use `rake clickhouse:migrate`
